service: serverless-nest-example

plugins:
  # - '@hewmen/serverless-plugin-typescript'  
  - serverless-plugin-optimize
  - serverless-offline
  # - serverless-plugin-warmup
  - serverless-plugin-typescript

# custom:
#   # Enable warmup on all functions (only for production and staging)
#   warmup:      
#       - production
#       - staging

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 30
  region: ap-southeast-1

package:
  individually: true

custom:
  serverless-offline:
    httpPort: 3000

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true

      - http:
          path: /
          method: ANY
          cors: true